;; Copyright (c) 2022, "the Phoeron" Colin J.E. Lupton <thephoeron@protonmail.com>
;; Released under the MIT License. See open-blackfire/LICENSE for more information.

(in-package :open-blackfire/quantum-cloud/ibm-quantum)

(defclass program-create ()
  ((name)
   (cost)
   (description)
   (spec)
   (public-p)
   (data))
  (:documentation ""))

(defclass program-response ()
  ((name)
   (cost)
   (description)
   (spec)
   (public-p)
   (id)
   (data)
   (creation-date)
   (update-date))
  (:documentation ""))

(defclass programs-response ()
  ((programs :type (vector program-response *))
   (count)
   (offset)
   (limit))
  (:documentation ""))

(defclass program-metadata ()
  ((name)
   (cost)
   (description)
   (spec)
   (public-p))
  (:documentation ""))

(defclass program-update ()
  ((name)
   (cost)
   (description)
   (spec))
  (:documentation ""))

(defclass job-run-params ()
  ((program-id)
   (hub)
   (group)
   (project)
   (backend)
   (params)
   (runtime)
   (log-level))
  (:documentation ""))

(defclass job-response ()
  ((id)
   (hub)
   (group)
   (project)
   (backend)
   (state :type job-state)
   (status :type job-status)
   (params)
   (program)
   (created)
   (runtime))
  (:documentation ""))

(defclass job-create-response ()
  ((id))
  (:documentation ""))

(defclass jobs-response ()
  ((jobs :type (vector job-response *))
   (count)
   (offset)
   (limit))
  (:documentation ""))

;; Replace this with a member type
(defclass job-status ()
  (())
  (:documentation ""))

(defclass job-state ()
  ((status)
   (reason))
  (:documentation ""))

(defclass error-container ()
  ((trace)
   (errors))
  (:documentation ""))

(defclass devices-response ()
  ((devices))
  (:documentation ""))

(defclass device-properties-response ()
  ())
  (:documentation ""))

(defclass device-configuration-response ()
  ()
  (:documentation ""))

(defclass device-defaults-response ()
  ()
  (:documentation ""))

(defclass device-status-response ()
  ((state)
   (status)
   (message)
   (length-queue)
   (backend-version))
  (:documentation ""))
